#ifndef RP2040_LORA_APRS_VARIANT_H
#define RP2040_LORA_APRS_VARIANT_H

#define LOG_LEVEL LOG_LEVEL_TRACE
//#define LOG_LEVEL LOG_LEVEL_VERBOSE

#define USE_ENERGY_DUMMY
//#define USE_FAKE_RF
#define USE_WATCHDOG
//#define USE_MPPTCHG
//#define USE_MPPTCHG_WATCHDOG
#define USE_WEATHER
#define USE_DIGIPEATER
#define USE_MESHTASTIC
//#define USE_WATCHDOG_MESHTASTIC // TODO
#define USE_LDR_BOX_OPENED
//#define USE_WATCHDOG_LINUX_BOARD
#define USE_I2C_SLAVE

#define INTERVAL_STATE 30000 // 30 secondes
#define INTERVAL_ENERGY 30000 // 30 secondes
#define INTERVAL_WEATHER 300000 // 5 minutes
#define INTERVAL_BLINKER 5000 // 5 secondes

#define WATCHDOG_MPPTCHG_INTERVAL_FEED_DOG 30000 // 30 seconds
#define WATCHDOG_MPPTCHG_TIME_POWER_OFF 10000 // 10 seconds
#define WATCHDOG_MPPTCHG_TIMEOUT 90 // 1,5 minutes

#define WATCHDOG_TIME_LORA_TX_OUT 1200000 // 20 minutes
#define INTERVAL_BOX_OPENED 120000 // 2 minutes

#define INTERVAL_TELEMETRY_APRS 900000 // 15 minutes
//#define INTERVAL_POSITION_AND_WEATHER_APRS 900000 // 15 minutes
#define INTERVAL_POSITION_AND_WEATHER_APRS 360000 // 60 minutes
#define INTERVAL_STATUS_APRS 86400000 // 1 day

#define LINUX_BOARD_PIN 1
#define MESHTASTIC_PIN 0
#define LDR_BOX_OPENED_PIN 2
#define WATCHDOG_MESHTASTIC_TIMEOUT 60000 // 1 minute
#define WATCHDOG_LINUX_BOARD_TIMEOUT 300000 // 5 minute
#define I2C_SLAVE_ADDRESS 0x55

#define APRS_CALLSIGN "F4HVV"
#define APRS_PATH "TEST,RFONLY"
#define APRS_DESTINATION "APLV1" // APL is LoRa : http://www.aprs.org/aprs11/tocalls.txt --> V1 is a new for this project
#define APRS_SYMBOL '-'
#define APRS_SYMBOL_TABLE '/'
#define APRS_LATITUDE 45.334528
#define APRS_LONGITUDE 5.619712
#define APRS_ALTITUDE 250
#define APRS_COMMENT "Test"
#define APRS_STATUS "Test"
#define APRS_TELEMETRY_IN_POSITION true

#endif //RP2040_LORA_APRS_VARIANT_H
